### ISSUE TITLE
./burp-suite-patch.sh: Permission denied

### ISSUE THREAD

**Issue by Drjacky** [mmgordon82/BurpSuiteInstaller#1]
```bash
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Patcher for Burp Suite Pro  100%
./burpsuite_pro_patcher_linux_generic.sh: line 701: ./burp-suite-patch.sh: Permission denied
```

**Comment by mmgordon82** [comment]
Hi there,
I would like to know more about your environment:
- What system are you running this on (`uname -a`)?
- What user is running this (`id`)?
- What shell ran this command (`/bin/bash | /bin/sh | Other`)?

Thank you for letting me know about this, I'll get right on that.

**Comment by mmgordon82** [comment]
I have found the culprit.
There was a problem with permissions when the makeself extracts itself.
It is now fixed, and I will be re-releasing the current version with the fix.
