### ISSUE TITLE
Patcher not working on my kali linux

### ISSUE THREAD

**Issue by LeonardOgendo** [mmgordon82/BurpSuiteInstaller#11]
when i run the patcher, it takes me to terms and when i click 'y' to accept the terms, i get an echo of 'command not found'
It's not even starting burp

**Comment by mmgordon82** [comment]
Can you send the output of the terminal, including the command line?
Also, how did you install burp?

By the way, I highly recommend you to add those types of Information (the context of the terminal, information about operating system etc) when opening issues in the future.

**Comment by LeonardOgendo** [comment]
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Success: '/opt/BurpSuitePro/jre/bin/java' can execute!
WARNING: package jdk.internal.org.objectweb.asm.Opcodes not in java.base
    ____                      __                    __             __ __
   / __ )__  ___________     / /   ____  ____ _____/ /__  _____   / //_/__  __  ______ ____  ____
  / __  / / / / ___/ __ \   / /   / __ \/ __ `/ __  / _ \/ ___/  / ,< / _ \/ / / / __ `/ _ \/ __ \
 / /_/ / /_/ / /  / /_/ /  / /___/ /_/ / /_/ / /_/ /  __/ /     / /| /  __/ /_/ / /_/ /  __/ / / /
/_____/\__,_/_/  / .___/  /_____/\____/\__,_/\__,_/\___/_/     /_/ |_\___/\__, /\__, /\___/_/ /_/
                /_/                                                      /____//____/
Github: https://github.com/h3110w0r1d-y/BurpLoaderKeygen 商业使用请购买正版软件！
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at com.h3110w0r1d.burploaderkeygen.KeygenForm.main(KeygenForm.java:424)

18. LAW AND JURISDICTION

The Licence, its subject matter or its formation (including non-contractual disputes or claims) shall be governed by and construed in accordance with English law and submitted to the exclusive jurisdiction of the English courts.
Do you accept the terms and conditions? (y/n)

Now when i accept the terms, it displays
18. LAW AND JURISDICTION

The Licence, its subject matter or its formation (including non-contractual disputes or claims) shall be governed by and construed in accordance with English law and submitted to the exclusive jurisdiction of the English courts.
Do you accept the terms and conditions? (y/n)
y
y: command not found
                                                                                
┌──(root㉿kali)-[~]
└─#

**Comment by LeonardOgendo** [comment]
is it my X11 variable

**Comment by LeonardOgendo** [comment]
Worked!
