### ISSUE TITLE
"No such file or directory" error!

### ISSUE THREAD

**Issue by MrDarkna** [mmgordon82/BurpSuiteInstaller#3]
Trying on Kali

It goes well until "press enter key to start burpsuit and the...."

Once I hit enter, after "[+] Starting the keygen...", it says no such file or directory on "./burp-suite-patch.sh: line 77"
And "...: line 79"
For /BurpSuitePro
And /jre/bin/java

And those files are RIGHT THERE with the actual BurpSuite installation! I've tried with and without 'Sudo' for both. Tried different directories... same error

How do I solve this?

Thank you for your work:) can't wait to use it!

**Comment by mmgordon82** [comment]
That's an interesting issue.
I would like to know more to replicate it myself:

Would you be so kind to attach the following additional info:
1. System information (`name -a`)
2. Distro Version (`cat /etc/os-rel*`)
3. MD5 checksum of the sh script
4. ls command showing the files really exist (and executing `file` on each)
5. Java version (`/jre/bin/java --version`)
6. (Optional, but recommended) execute the sh with `strace` (`sudo strace ./burp-suite-patch.sh`)

It does seem like much but would really help me understand why it happens...

Thanks,
Maor

**Comment by mmgordon82** [comment]
Hi, 

Next time, for better readability, put code/command output in code blocks (see [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting))

The strace shows it might be a weird issue with a missing `rm` command. 

1. When you run `which rm` do you see the binary? Where? 
2. If not, look for it (`find / -xdev -name rm`)

It might be an issue with PATH environment variable...

**Comment by MrDarkna** [comment]
`which rm
/usr/bin/rm
`
I'm a beginner :D clearly. That's why I want the pro, since the book i'm reading uses that version.

Could you please help me on how I could solve this? If that's possible and not too complex

**Comment by mmgordon82** [comment]
Sure. As a beginner I also liked to have the Pro version lol.

Let's see your PATH environment variable (`echo $PATH`).

**Comment by MrDarkna** [comment]
Thank you haha appreciate it!

`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games`

**Comment by MrDarkna** [comment]
I just tried installing it on Mint linux and face the exact same error.
Seems to be an issue with he keygen itself

**Comment by mmgordon82** [comment]
Hi,
I still didn't manage to replicate the problem, didn't try on Mint tho.
If possible, try running the script with `strace` again, This time add the flag `-f` to the strace like so:
`sudo strace -f --output=burp-patch.log ./burp-suite-patch.sh`
This time it will also strace the forks and children of the original process (maybe I'm missing something here).
Upload burp-patch.log when finished.

BTW what instructions were you following when you install burp? 

Thanks.

**Comment by mmgordon82** [comment]
By the way, I just fixed the CI/CD so feel free to try the latest Burp version. Let me know if the issue persists.

**Comment by mmgordon82** [comment]
Due to inactivity for two weeks and being unable to fully reproduce the bug, I'm closing the issue.
