### ISSUE TITLE
Script Does Nothing on Kali Linux 2023.3

### ISSUE THREAD

**Issue by burpist** [mmgordon82/BurpSuiteInstaller#6]
Tried the latest linux patcher script, 2023.10.3.5. It it instantly fails, as if it doesn't even complete the search function:
```
./burpsuite_pro_patcher_linux_generic.sh
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Patcher for Burp Suite Pro  100%  
[+] Finding Burp Suite Installations...
[!] Couldn't find the Burp Suite installation.
    Make sure you have Burp Suite installed and try again.
    If you have Burp Suite installed, try running this script with the vmoptions as an argument.
    Example: ./burp-suite-patch.sh /opt/BurpSuitePro/BurpSuitePro.vmoptions
```

Background
- Fresh install of Burp Suite Pro 10.3.6 (Linux ARM64)
- Downloaded latest patcher script, v2023.10.3.5
- Made patcher file executable
- Executed normally and with sudo
- Output is exactly same as above, script doesn't initialize find it seems and fails to recognize the manual install method

*I did find that a previous version of the script (version unknown) does work, but won't patch Burp Suite 10.3.6*

uname -a
```
Linux XXXXXXXXX 6.5.0-kali3-arm64 #1 SMP Debian 6.5.6-1kali1 (2023-10-09) aarch64 GNU/Linux
```

cat /etc/os*
```
RETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.3"
VERSION="2023.3"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

**Comment by Porygon31** [comment]
Work fine for me

![Capture d’écran_Cropped_2024-03-18_04-09-34](https://github.com/mmgordon82/BurpSuiteInstaller/assets/85462132/75eb94e5-6559-44af-bf83-40c8782cad26)

**Comment by renyoutianming** [comment]
need sudo run shell code
:)

**Comment by mmgordon82** [comment]
Hi,
Recent versions of the Linux patcher now allow specifying a path to a particular BurpSuite installation. Please note, this crack is effective only when using the installer from [PortSwigger's website](https://portswigger.net/burp/releases#professional), not with standalone JAR files.

As detailed in the [patcher bash script](https://github.com/mmgordon82/BurpSuiteInstaller/blob/main/linux/burp-suite-patch.sh#L5), you can provide a path directly to a vmoptions file or to a directory where Burp Suite is installed.

If you installed using the official installer, you can run the script like this:

```bash
./burpsuite_pro_patcher_linux_generic.sh /your/path/to/burp/suite
```

Ensure that the script is executed with the same permissions as those used for the installer.
