### ISSUE TITLE
thx u

### ISSUE THREAD

**Issue by Kaiddd** [mmgordon82/BurpSuiteInstaller#7]
Thx u works great on latest burp as of 12/15/23

**Comment by mmgordon82** [comment]
Glad to hear!
Happy bug-bounty hunting!

**Comment by sleepyhollow81** [comment]
the key gen doesn't give a valid key to use at all and I know I did every thing correctly but when I try to activate it per the instructions it fails every time

**Comment by Kaiddd** [comment]
> the key gen doesn't give a valid key to use at all and I know I did every thing correctly but when I try to activate it per the instructions it fails every time 

Go make an issue then, other issues are not the place to comment
