### ISSUE TITLE
Linux Does not decrypt Generated Response 

### ISSUE THREAD

**Issue by Satanaelcode** [mmgordon82/BurpSuiteInstaller#9]
### Request
`MEWdBTubqdSerc1KqOm5fc1UKjmIqpa388ov+Vw02mqiLc/Gz7p2/Be5/VxrE+sLtSSjhdmVOovFsawJa5w4UDDwsqzv25cfTPRxa4JPZr5+esc+H4PUwe/+lS4SRASxnIn1uh1iNxCoWqfJaK2yNUCMC2EspKKpt5pbtry5pbJScgh6BCU+TVdZHGevkPLzYQdqvLbbdHqBpDVjVL15s/FePPqRuOK6XD0mO17fybvGoDBUGNxe3r3gq7X+4wnt7T1SH3AO3eX60CHBVbCAm7DgVKTQBDo4pwOFFoqJGa8w5gQ/txe+XV72/QLX7f7I5MXXBc+3I2EaXkBFHqyyeCvsNYJJDFMB`

### Response
`BTavGLRKGXN6UykcbcH4sn4PHDFaqnkiqCJ/nuXrSUYJItgGcL3F4sl5kBVXy2PrFzXmqv5ERiefFNZ3AhJQ08ZMMGDARBdzvrK8Bzgbxug5twkzw8qjgKGmFVT/vivgnwsG/QbJuax7V0BgareE5wusIJhd5uNJyeh72M61YtcbmVTwNaO/50nFc/Ki7cyqiaXI2n7oUDVAesLJp9ThSlGl22O4/SsLWm0msmAe4d/YZorGXF6TLV1yrYAsMFmn9Y6duhr6zGD2xOaDcxVqFKnjW8NrPF9aR7b2ZpnzhIiMi6+6m0N1ajJEMWJ5hqEzsPS2RNpU8ECz1LYHNt7TN7TdpxKfYsEXA17522N5ZVTdS5274DIh1sEpki0JCrV7j3kEyNipIxxpfhhEkca+VwU5puyqMywdY9KelQUfbiJT51cj7W6qOmH51Dz0bgWRDzNzx+IiqYh40uWijoSRGAUHYBMFvTIM/jLTWl3lau5lWjPMDVJS19h+PzNMiC3VCqtJ4fNj2p9qpGhDuDNR0YIj8Dbvg6F7OasaXoVZlmBOxPyhm7qAoV0IFJMDrFflYAwtSze1tgUySOOT/dTw6MEPZsSidH5leTMbT/6RSnV8oUw3C3NSp9Py+FWvoibvgAKCqD2H/dZQ/7AtsJE5FPuQr5pFgzN8Fe9rfvwCud/kkQDpfChwwkkPiruZHwwrjoejxUTjMLB1xm60/F3usmnO8KtNLwlvfGdKHOedDUv9gnWmwoNg0BYtnmna4LrWM5CUmngKd9SohGSsGncZt+1trKi8QcQ471lWdejg27frOn0iFo0D0nm6ny142xP3Q/sSj+al9wFDQsDDQHuBRKTCAEPEHfhv9+KO+2CT8UsPrb4gLCKEp7xL/Ge9Fu0c`

### Returned Error
**Error decoding activation request :-(**

**Comment by mmgordon82** [comment]
Interesting. It looks like a common case of the `javaagent` not loading correctly to Burp runtime.

I'd try the following:

1. Uninstall Burp suite, don't forget to [delete the cache and configurations](https://github.com/mmgordon82/BurpSuiteInstaller?tab=readme-ov-file#linux-1)
2. Follow the instructions in [Getting Started for Linux](https://github.com/mmgordon82/BurpSuiteInstaller?tab=readme-ov-file#download-and-install)

If the problem persists, upload the following information:

- `uname -a`
- The location where Burp is installed
- Try running burp with the CLI, and send the logs it shows in the terminal

**Comment by Satanaelcode** [comment]
fixed it its fine 
just reinstalled burp
